<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MSI" ignored="0" name="SeleniumAutomationTesting" tests="3" failures="2" timestamp="29 Jan 2022 13:05:58 GMT" time="14.119" errors="0">
  <testcase name="runScenario" time="7.48" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <skipped/>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="7.609" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at steps.mySteps.userValidates(mySteps.java:50)
at ✽.user validates(file:///D:/workspace/SeleniumAutomationTesting/src/test/java/features/sampleFeature.feature:7)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="6.145" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at steps.mySteps.userValidates(mySteps.java:50)
at ✽.user validates(file:///D:/workspace/SeleniumAutomationTesting/src/test/java/features/sampleFeature.feature:13)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- SeleniumAutomationTesting -->
