<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="MSI" name="runner.TestRunner" tests="3" failures="2" timestamp="29 Jan 2022 13:05:58 GMT" time="21.234" errors="0">
  <testcase name="runScenario" time="7.609" classname="runner.TestRunner">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at steps.mySteps.userValidates(mySteps.java:50)
at ✽.user validates(file:///D:/workspace/SeleniumAutomationTesting/src/test/java/features/sampleFeature.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="6.145" classname="runner.TestRunner">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at steps.mySteps.userValidates(mySteps.java:50)
at ✽.user validates(file:///D:/workspace/SeleniumAutomationTesting/src/test/java/features/sampleFeature.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="7.480" classname="runner.TestRunner">
    <skipped/>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.TestRunner -->
